### ISSUE TITLE
complete example or source of your blog

### ISSUE THREAD

**Issue by marekyggdrasil** [bradhowes/remarkable-katex#1]
hello,
good work with developing a great plugin! I'm excited to try it out, however I am having trouble properly displaying the rendered formulas

I include the plugin in my react project just as you instructed [here](https://github.com/bradhowes/remarkable-katex#to-use), however the formula does not render properly, for instance for the input

```
$$\sqrt{a}$$
```

I get this html

```html
<span class="katex-display"><span class="katex"><span class="katex-mathml"><math>
<semantics>
	<mrow>
		<msqrt>
			<mrow>
				<mi>
					a
				</mi>
			</mrow>
		</msqrt>
	</mrow>
	<annotation encoding="application/x-tex">
		\sqrt{a}
	</annotation>
</semantics></math></span><span aria-hidden="true" class="katex-html"><span class="strut" style="height:0.8491550000000001em;"></span><span class="strut bottom" style="height:1.04em;vertical-align:-0.190845em;"></span><span class="base displaystyle textstyle uncramped"><span class="mord sqrt"><span class="sqrt-sign" style="top:-0.009155000000000024em;"><span class="style-wrap reset-textstyle textstyle uncramped">√</span></span><span class="vlist"><span style="top:0em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:1em;">​</span></span><span class="mord displaystyle textstyle cramped"><span class="mord mathit">a</span></span></span><span style="top:-0.769155em;"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:1em;">​</span></span><span class="reset-textstyle textstyle uncramped sqrt-line"></span></span><span class="baseline-fix"><span class="fontsize-ensurer reset-size5 size5"><span style="font-size:1em;">​</span></span>​</span></span></span></span></span></span></span>
```

And renders as

<img width="143" alt="screen shot 2018-03-16 at 7 53 47 pm" src="https://user-images.githubusercontent.com/8202674/37549145-c89f1a1c-2953-11e8-9dc9-4ed894a0b71a.png">

I am guessing stylesheet or client side javascript might be missing, I'm not entirely sure how to inclue all that using `remarkable`

Could you maybe share source of your blog or some more complete example?

**Comment by bradhowes** [comment]
Hi Marek. The entire source of my blog, including the use of this plugin with Remarkable is in my repo at https://github.com/bradhowes/keystrokecountdown -- see the build.js file for the Metalsmith processing chain I use to render KaTex.

**Comment by bradhowes** [comment]
Yes, you definitely need to load katex.css. The build.js script builds one CSS file from those in the src/css directory (as well as one Javascript file from those in the src/js directory).

**Comment by marekyggdrasil** [comment]
All clear! Wanted to make sure if I have to do it myself or if `remarkable-katex` will do it for me, I got my answer.

Thanks for quick feedback and for source of your blog! Cheers!
