### ISSUE TITLE
how could i implemet render tikz-pictures

### ISSUE THREAD

**Issue by leoluu** [bradhowes/remarkable-katex#3]
hi, thinks for this project, is it could render this
$$\begin{tikzpicture}[scale=1.0544]\small
\begin{axis}[axis line style=gray,
	samples=120,
	width=9.0cm,height=6.4cm,
	xmin=-1.5, xmax=1.5,
	ymin=0, ymax=1.8,
	restrict y to domain=-0.2:2,
	ytick={1},
	xtick={-1,1},
	axis equal,
	axis x line=center,
	axis y line=center,
	xlabel=$x$,ylabel=$y$]
\addplot[red,domain=-2:1,semithick]{exp(x)};
\addplot[black]{x+1};
\addplot[] coordinates {(1,1.5)} node{$y=x+1$};
\addplot[red] coordinates {(-1,0.6)} node{$y=e^x$};
\path (axis cs:0,0) node [anchor=north west,yshift=-0.07cm] {0};
\end{axis}
\end{tikzpicture}$$

just like https://upmath.me/,
https://github.com/parpalak/upmath.me

**Comment by bradhowes** [comment]
Hi,

I have no experience with tikz library, and from my limited search it appears to be something that would take a lot of work. See https://github.com/KaTeX/KaTeX/issues/219

Perhaps there is some other way to achieve this? I have no idea.

Regards,

Brad

-- 
Brad Howes
Skype: br.howes
