### ISSUE TITLE
open (escaped) curly brace will not parse

### ISSUE THREAD

**Issue by marcusdemoura** [bradhowes/remarkable-katex#6]
Open curly brace (without a matching "closing" brace) will break the parse even when escaped.

I need something like this:
![Screen Shot 2021-05-12 at 11 16 33](https://user-images.githubusercontent.com/6610831/117990571-a80b5e80-b313-11eb-8c67-7584f6576520.png)

I'm getting the string from a json file like this:
`$\\left\\{ \\begin{matrix}a + b +  b = c \\\\ a + b = c\\end{matrix}\\right.$` won't parse

`$\\left[ \\begin{matrix}a + b +  b = c \\\\ a + b = c\\end{matrix}\\right.$` parses correctly

Changing the parser on lines 100 and 102 like this will make it work:

```
while (pos < max) {
      const char = state.src.charAt(pos);
      if (char === '{' && state.src.charAt(pos-1) !== '\\') {
        escapedDepth += 1;
      } else if (char === '}' && state.src.charAt(pos-1) !== '\\') {
        escapedDepth -= 1;
        if (escapedDepth < 0) { return false; }
```

I'm not very familiar with katex/math so i'm not sure if it would break something else, but i can make a PR with the change if that's ok!

**Comment by bradhowes** [comment]
Thanks for posting your detailed issue and fix. I slightly modified it and committed your change along with two unit tests.

**Comment by marcusdemoura** [comment]
Thanks for the fast response!
Do you have a ETA for publishing on NPM?

**Comment by bradhowes** [comment]
Marcus,

I pushed a new version out. Please let me know if there are any issues. Thanks again!

Regards,

Brad
